### PR TITLE
Suggested edits to data

### PR DESCRIPTION
**Pull request by parulsingh23**
Hello there! I used Mavo to suggest the following edits:
I added a note that JS was supported in expressions until v0.2.1
Preview my changes here: https://mavo.io/docs/expressions?storage=https%3A%2F%2Fraw.githubusercontent.com%2Fparulsingh23%2Fmavo.io%2Fmaster%2Fdocs%2Fdocs.json&docs-storage=https%3A%2F%2Fgithub.com%2Fmavoweb%2Fmavo.io%2Fdocs%2Fdocs.json

### CODE REVIEW

**Comment by LeaVerou** [comment]
@DmitrySharabin Do you know why there are conflicts here? Parul sent a PR that was merged, and then she made a few more changes. Is this something we could fix in the PR plugin?

**Comment by DmitrySharabin** [comment]
Hm 🤔 I don’t know. I’ll have a look at it. I hope we could fix it; this is the reason why I always remove the `mavo.io` fork before submitting a new PR.

**Comment by DmitrySharabin** [comment]
@LeaVerou I believe we could avoid this issue (merge conflicts) if before committing into an existing PR, we check if the corresponding PR is already merged. And if yes, we could automatically close the merged PR and open a new one with the newly added commit. I looked through the Github API, and there are corresponding requests. What do you think of this approach?

**Comment by LeaVerou** [comment]
@parulsingh23 did you mean to close this?

**Pull request closed without merging**
