### PR TITLE
Use the transpiled Mavo

### PR DESCRIPTION
**Pull request by DmitrySharabin**
Let's make our demos available on more browsers.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Should we use minified though? Is there a chance people may want to look at the code?

**Comment by DmitrySharabin** [comment]
Right! Good point.

And since the ES5 code might be over-complicated, what if we just leave it as it is and close the PR? What do you think?

**Comment by LeaVerou** [comment]
I'm not sure. I can certainly see the benefit of supporting a wider array of browsers, and of minifying.
@karger, what do you think?

**Comment by karger** [comment]
I suspect most people looking at the demos will look at the HTML, not the js.   I'd advocate for as many people as possible being able to run the demos.

**Comment by LeaVerou** [comment]
Ok, then, I concur. Merged!

**Pull request merged**
