### PR TITLE
Suggested edits to data

### PR DESCRIPTION
**Pull request by code-reaper08**
### Hello there! I used Mavo to suggest the following edits:
I added a short description for "localStorage" for non-programmers.
Preview my changes here: https://mavo.io/docs/storage?docs-storage=https%3A%2F%2Fraw.githubusercontent.com%2Fcode-reaper08%2Fmavo.io%2Fmaster%2Fdocs%2Fdocs.json

**Please ping me if it needs any further improvements**

### CODE REVIEW

**Comment by LeaVerou** [comment]
@DmitrySharabin Do you know why the preview here doesn't work?

@code-reaper08 I'm going to review here, because the addition is all on one line, so the Github review UI isn't helpful.

> `localStrorage` is in simple term is

Double "is", also the expression is "in simple term**s**"

> a persistent form of storing data.

As opposed to the other storage methods which are not persistent?
Most storage methods are persistent, with few exceptions. The difference is that localStorage is stored locally, in the browser, and not on a server. It would also be useful to point out that data stored in localStorage will not be available in other browsers on the same device, or even a private browsing (incognito) tab in the same browser.

> The data stored here is available permanently, 

No, it's not. If you clear private data, localStorage will be cleared too.

> and it is read-only. 

No it's not! That would make it *significantly* less useful.

> In simple terms data here is not lost when the browser's tab is closed.

Again, that applies to almost all storage methods.

**Review by LeaVerou — CHANGES_REQUESTED** [review]
See comment

**Comment by code-reaper08** [comment]
## Hello @LeaVerou 😄  
I think the mistake is I've compared `localStorage` to `sessionStorage` and I completely missed the server side way of storing data, which probably caused chaos (much general description leaving important info behind) in my edit. Thanks for your patience on pointing out each and everything in detail. It really helps me a lot 🙏😁  

And the grammar mistake of **is**, I'll take care of that too. (It feels silly).  

### Thanks for this, I'll come up with changes as you said.

**Comment by DmitrySharabin** [comment]
> Do you know why the preview here doesn't work?

@LeaVerou Lea, I believe I've found the root of the problem. The problem is that we have both `mv-storage` and `mv-source` on every docs page.

https://github.com/mavoweb/mavo.io/blob/2479df258e81d518a66b51e0b12e2717e27977f2/docs/page/index.tpl.html#L5

And since in the `Mavo#load` method we prefer `source` over `storage`, we load `/docs/docs.json` instead of the `docs.json` that is stored in a user's fork (see [line 510 in the `Mavo#load` method](https://github.com/mavoweb/mavo/blob/526639a8b1f27601cf7690da5083e5325c299c49/src/mavo.js#L510)).

I already know how to fix it (in the Github PR plugin): I'll add the `appId-source` search param to the preview URL if the corresponding app has `source`.

I'll test it and will send a PR to the plugins repo.

**Comment by code-reaper08** [comment]
## Hello @LeaVerou 
Please check this **[commit](https://github.com/mavoweb/mavo.io/pull/113/commits/f6ec9122204982037ab2a554d08e3fe7a289e819)**

Is it OK, or should I improve it some more ?

I would be glad to do any further additions if needed 😁✨

**Review by LeaVerou — CHANGES_REQUESTED** [review]
A few (mostly) minor corrections:

- Opening paren needs space before it
- "Incognito" and "Google Chrome" are proper nouns and need to be capitalized
- It's grammatically incorrect to say "in the `localStorage`". Drop the "the", just "data in `localStorage`"
- Use "until" instead of "till"
- I'd drop "Unlike cookies, it does not affect the website's performance.", this is a detail that is not particularly relevant
- Drop "localStorage can store only strings. Any other data type needs to be converted to a string manually before storing.", this is not actionable by our users, and Mavo takes care of serializing non-strings anyway.

**Comment by code-reaper08** [comment]
## Hello @LeaVerou 😄

Could you please look at this **[commit](https://github.com/mavoweb/mavo.io/pull/113/commits/ef03a919eaf682d532356246940f2f40db32e3cc)**?

Is it any better than before?

**Review by LeaVerou — CHANGES_REQUESTED** [review]
I'd actually join the first two sentences: `localStorage` is a persistent form of storing data locally in the user's browser. Data stored in `localStorage` is not accessible..."

I'd also drop the last sentence ("It is advised..."), first because Mavo users don't deal with storing passwords (Mavo does it for them) so it's non actionable to them, and secondly because it's unclear why to avoid this in localStorage in particular, which is actually far more private than cookies for example since its data is not sent over the wire. Passwords should not be stored in plain text anywhere, but localStorage is not unique in that respect, and this conversation is completely out of scope for this section.

**Comment by code-reaper08** [comment]
> I'd actually join the first two sentences: `localStorage` is a persistent form of storing data locally in the user's browser. Data stored in `localStorage` is not accessible..."
> 
> I'd also drop the last sentence ("It is advised..."), first because Mavo users don't deal with storing passwords (Mavo does it for them) so it's non actionable to them, and secondly because it's unclear why to avoid this in localStorage in particular, which is actually far more private than cookies for example since its data is not sent over the wire. Passwords should not be stored in plain text anywhere, but localStorage is not unique in that respect, and this conversation is completely out of scope for this section.

## Hello @LeaVerou 😃

I've changed the necessary things as you mentioned, please have a look at this **[commit](https://github.com/mavoweb/mavo.io/pull/113/commits/827ea77439544939861833bad68565682ad0a789)**.

**Comment by LeaVerou** [comment]
The text itself looks fine now, but the diff is messed up, and has changes from another commit…

**Comment by code-reaper08** [comment]
> The text itself looks fine now, but the diff is messed up, and has changes from another commit…

I am a bit confused, how does it happen ?
Should I edit it again (the same text) and create a PR ?

Will it do good ?

**Comment by code-reaper08** [comment]
## Hello @LeaVerou 😄

Would it be fine if I again commit my changes?

**Comment by LeaVerou** [comment]
Unfortunately, this is a common issue, and why we moved the PR stuff to a plugin :(

You could either rebase manually, or delete the fork that Mavo created, and do the changes again via the website.
The latter is probably easier.

**Comment by code-reaper08** [comment]
I'll close this PR, as I've created a new PR [here](https://github.com/mavoweb/mavo.io/pull/118)

Please check it out 💯

**Pull request closed without merging**
