### PR TITLE
Documentation about mv-edit-type

### PR DESCRIPTION
**Pull request by DmitrySharabin**
Hello there! I used Mavo to suggest the following edits:
I added The mv-edit-type attribute section to the docs and to the index of all attributes.
Preview my changes here: https://mavo.io/docs/properties?docs-storage=https%3A%2F%2Fraw.githubusercontent.com%2FDmitrySharabin%2Fmavo.io%2Fmaster%2Fdocs%2Fdocs.json&docs-source=none

### CODE REVIEW

**Comment by DmitrySharabin** [comment]
There is one thing I'm not sure about: Whether the `mv-edit-type` attribute is _live_ or not? I looked through the source code and assumed that it's not. Not even _initially_. Am I right?

**Review by LeaVerou — APPROVED** [review]
I'm going to accept this because it's better to have some documentation that not, but do note that `mv-edit-type` doesn't just do that. E.g. `mv-edit-type="self"` is still useful, to avoid **both** editing UIs. Also, we need to note that this is experimental, and only available in the unreleased version (though we can probably note this in the description, not the index).

**Comment by LeaVerou** [comment]
I hadn't seen the actual paragraph when I wrote the comment above, only the index entry. Great work @Dmitry!!

**Comment by LeaVerou** [comment]
> There is one thing I'm not sure about: Whether the `mv-edit-type` attribute is _live_ or not? I looked through the source code and assumed that it's not. Not even _initially_. Am I right?

Ha, good question. The current behavior is quite buggy: if the property changes while the element is in read mode, it works just fine and is live. But if it changes while in edit mode, *weird* things happen.
See testcase: https://codepen.io/leaverou/pen/ExZbvNx?editors=1100

I'll open a new issue.

**Pull request merged**
