### PR TITLE
Adopt new syntax for collections

### LINKED ISSUE #155: Documentation: Primer uses deprecated mv-multiple
In the documentation  at mavo.io, the Primer shows how collections work using the 'mv-multiple' attribute.  The Collections documentation states that mv-multiple is deprecated in favour of mv-list.  However the Collections documentation also uses 'mv-multiple' further down the page under the heading "Simple and complex collections", as the first method described.  It's likely that new users ill focus on the deprecated approach.  

It would be good to update the Primer to show the use of mv-list, and move the deprecated approach down the Collections page.

### PR DESCRIPTION
**Pull request by DmitrySharabin**
* The main page +  the corresponding demos
* The Primer page
* The Collections page of the docs

Closes #155.

UPDATE:

* All demos
* All pages
* Docs

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks! Can you enable deploy previews on Netlify, so I could review this on the actual website?

**Comment by DmitrySharabin** [comment]
> Thanks! Can you enable deploy previews on Netlify, so I could review this on the actual website?

[They already are](https://deploy-preview-156--mavoio.netlify.app/). But to see the changes, you might need to use Requestly to redirect the stable version of Mavo (which we use on the site) with the dev version.

One more thing to consider: to see actual data on the API page, please follow this link: https://deploy-preview-156--mavoio.netlify.app/docs/api/?storage=api.json#Mavo.Collection.

**Comment by LeaVerou** [comment]
> > Thanks! Can you enable deploy previews on Netlify, so I could review this on the actual website?
> 
> [They already are](https://deploy-preview-156--mavoio.netlify.app/). But to see the changes, you might need to use Requestly to redirect the stable version of Mavo (which we use on the site) with the dev version.

Huh, why does netlify bot not comment here with the deploy preview? Do we need to do something else for that?

**Comment by DmitrySharabin** [comment]
> > > Thanks! Can you enable deploy previews on Netlify, so I could review this on the actual website?
> > 
> > 
> > [They already are](https://deploy-preview-156--mavoio.netlify.app/). But to see the changes, you might need to use Requestly to redirect the stable version of Mavo (which we use on the site) with the dev version.
> 
> Huh, why does netlify bot not comment here with the deploy preview? Do we need to do something else for that?

I enabled one more notification, so It should be working now.

IMG_1736

**Comment by DmitrySharabin** [comment]
## The main page

Main Page

Main Page — Tooltip (mv-list)

Main Page — Tooltip (mv-list-item)

## Primer

Primer — Collections

Primer — Expressions and Lists

## Collections

Collections — mv-list

Collections — mv-multiple

## Properties

Properties

**Comment by DmitrySharabin** [comment]
I wonder whether we should teach users of the old stuff about collections: it feels like we should tell about it inside the collections part of the docs, but in other places, we should probably stick with `mv-list`/`mv-list-item`. What do you think?

**Comment by LeaVerou** [comment]
Thank you!

I've also been thinking that instead of deprecating `mv-multiple` we should perhaps keep it as a shortcut? Then the docs could say something like "and in Mavo versions until v0.2.4 it was the *only* way to define collections". 
Especially since sometimes it's completely non-obvious what container you can use (`<select>` comes to mind, where you often want the `<select>` itself to be a primitive property, but populate its options via a collection — what's the `mv-list` element here?).
Also, there were several advantages of the `mv-list` approach (see https://github.com/mavoweb/mavo/issues/72 ) so perhaps we should mention some of these? E.g. with `mv-multiple` there was no clear way to distinguish which properties apply to the whole collection, and which to the item.

**Comment by karger** [comment]
I thought it was an exact synonym for mv-list-item, so how would it be a shortcut for anything?

**Comment by LeaVerou** [comment]
> I thought it was an exact synonym for mv-list-item, so how would it be a shortcut for anything?

It's not, as you can see [here](https://github.com/mavoweb/mavo/blob/master/src/mavo.js#L1076).
Because `mv-multiple` represented both the collection and the collection item, it took attributes that applied to either, and need to be moved to different elements when doing the rewriting. Whereas `mv-list-item` is *always* the item, and any attributes on it only apply to the list item.

I don't think we need the weirdness of mv-multiple. If they don't know what container to use for mv-list or mv-list-item, they can just leave them out and as long as they specify at least one, their collection will be created.

**Comment by LeaVerou** [comment]
After mulling it over some more, I think we should continue to deprecate `mv-multiple`, but frame only using `mv-list-item` or only `mv-list` as an option if authors don't need to specify both, rather than an authoring mistake that we handle.

**Comment by DmitrySharabin** [comment]
> Apart from that, my only comment is to clearly mark that this is only available starting from v0.3.0, which I don't see right now? (no need to say this in the front page or Primer but we should in the Collections page).

I made it a bit more prominent. Is it enough now? Or should we have something different?

image

> After mulling it over some more, I think we should continue to deprecate `mv-multiple`, but frame only using `mv-list-item` or only `mv-list` as an option if authors don't need to specify both, rather than an authoring mistake that we handle.

Will something like this be enough?

image

I also added these parts to the Collections page:

image

image

**Comment by LeaVerou** [comment]
LGTM, thank you! The text explaining what you can omit is a little verbose/convoluted, but we can fix that later.

**Review by LeaVerou — APPROVED** [review]

**Comment by LeaVerou** [comment]
> I recommend that we replace "collection" with "list" everywhere in the documentation. We have implemented (ordered) lists not (unordered) collections and our syntax is mv-list, so let's be consistent with that.

Agreed

**Comment by DmitrySharabin** [comment]
Will try to do it asap.

**Comment by karger** [comment]
I don't think that we should use the primary documentation to explain why we used to do things differently and why we changed.   It will be confusing/irrelevant for most users.  If we want the explanation it should go in a footnote or something.




> > Apart from that, my only comment is to clearly mark that this is only available starting from v0.3.0, which I don't see right now? (no need to say this in the front page or Primer but we should in the Collections page).
> 
> I made it a bit more prominent. Is it enough now? Or should we have something different?
> 
> image
> > After mulling it over some more, I think we should continue to deprecate `mv-multiple`, but frame only using `mv-list-item` or only `mv-list` as an option if authors don't need to specify both, rather than an authoring mistake that we handle.
> 
> Will something like this be enough?
> 
> image
> I also added these parts to the Collections page:
> 
> image
> > Also, there were several advantages of the mv-list approach (see [mavoweb/mavo#72](https://github.com/mavoweb/mavo/issues/72) ) so perhaps we should mention some of these? E.g. with mv-multiple there was no clear way to distinguish which properties apply to the whole collection, and which to the item.
> 
> We already had this:
> 
> image
> And also added this:
> 
> image

**Comment by karger** [comment]
> After mulling it over some more, I think we should continue to deprecate `mv-multiple`, but frame only using `mv-list-item` or only `mv-list` as an option if authors don't need to specify both, rather than an authoring mistake that we handle.
> 
> Which means we can omit it from our own examples too when it's obvious, and not output a warning for it. (maybe `console.info()`?)
> 
> Apart from that, my only comment is to clearly mark that this is only available starting from v0.3.0, which I don't see right now? (no need to say this in the front page or Primer but we should in the Collections page).

What if we frame this by introducing collections using only the mv-list (or only the mv-list-item) attribute, but then follow by explaining that if a user needs more fine-grained configuration (ie some config of the collection and some config of its items) then they can make use of [other attribute] in combination.

**Comment by DmitrySharabin** [comment]
> > I recommend that we replace "collection" with "list" everywhere in the documentation. We have implemented (ordered) lists not (unordered) collections and our syntax is mv-list, so let's be consistent with that.
> 
> Agreed

It'll become a bit (much) easier to accomplish if we fix [this issue](https://github.com/mavoweb/mavo/issues/984). 😉

**Comment by DmitrySharabin** [comment]
Will continue working on it after releasing `v0.3.0`. We need this PR to be merged for our site to work correctly.

**Pull request merged**
