### PR TITLE
Fix styling issues and some other enhancements

### PR DESCRIPTION
**Pull request by DmitrySharabin**
This PR should get the site ready for the upcoming version of Mavo, fix some issues with styles, and make page editing more consistent (no more always-visible mavo bar).

### CODE REVIEW

**Comment by DmitrySharabin** [comment]
Here are some screenshots so that it could be easier to notice the changes:

### Before
Screen Shot 2021-07-12 at 16 45 00

### After
Screen Shot 2021-07-12 at 16 45 09

### Before
Screen Shot 2021-07-12 at 16 35 21

### After
Screen Shot 2021-07-12 at 16 34 34

### Before
Screen Shot 2021-07-12 at 16 42 14

### After
Screen Shot 2021-07-12 at 16 43 06

### Before
Screen Shot 2021-07-12 at 16 43 46

### After
Screen Shot 2021-07-12 at 16 43 57


### Before
Screen Shot 2021-07-12 at 16 39 35

### After
Screen Shot 2021-07-12 at 16 39 46

### Before
Screen Shot 2021-07-12 at 16 40 41

### After
Screen Shot 2021-07-12 at 16 40 19

### Before
Screen Shot 2021-07-12 at 16 41 20

### After
Screen Shot 2021-07-12 at 16 41 08

**Comment by DmitrySharabin** [comment]
Btw, it will also fix #111.

**Comment by LeaVerou** [comment]
Thanks, merged!

(can't wait until we can use `:is()` for these repetitive selectors...)

**Comment by DmitrySharabin** [comment]
Me too! I was very anxious to use it but didn't venture to do it now.

**Pull request merged**
