### PR TITLE
Some enhancements to the demos homepage

### PR DESCRIPTION
**Pull request by DmitrySharabin**
What I did:
- split all demos into two categories: _Basic demos_ and _Complex demos_
- refactored `demos.json` to make the first point happen
- converted the _Mavo in the wild_ section into a separate app so that we could work with it effortlessly. We need to update it eventually btw (see https://github.com/mavoweb/mavo/issues/726).

Please feel free to rearrange the demos the way you like. I'm not sure I've split them the way you imagined. :)

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thank you Dmitry. You split them perfectly. I wonder if we should have a third category: "Full applications" for things like the memory game or the SVG Path that are even more complex. 
Could you post a screenshot so I could review the visual changes too?

**Comment by DmitrySharabin** [comment]
You can review the visual changes here:

https://deploy-preview-137--mavoio.netlify.app/demos?demos-source=https://raw.githubusercontent.com/mavoweb/mavo.io/split-demos/demos/demos.json&mavos-source=https://raw.githubusercontent.com/mavoweb/mavo.io/split-demos/demos/mavos.json

**Comment by DmitrySharabin** [comment]
> I wonder if we should have a third category: "Full applications" for things like the memory game or the SVG Path that are even more complex.

Excellent idea. Let me do that now.

**Comment by DmitrySharabin** [comment]
Done!

Here is the new URL to preview the changes:
https://61afa99a60f3c40007481e36--mavoio.netlify.app/demos/?demos-source=https://raw.githubusercontent.com/mavoweb/mavo.io/split-demos/demos/demos.json&mavos-source=https://raw.githubusercontent.com/mavoweb/mavo.io/split-demos/demos/mavos.json

**Comment by LeaVerou** [comment]
Looks great, apart from one thing: The contrast between the orange summary and the gray background is not great. I think blue would be better.

**Comment by DmitrySharabin** [comment]
We definitely need to fix some issues with the mobile layout.

Screen Shot 2021-12-07 at 21 57 03

Screen Shot 2021-12-07 at 21 57 17

**Comment by DmitrySharabin** [comment]
> Looks great, apart from one thing: The contrast between the orange summary and the gray background is not great. I think blue would be better.

I was beating up and down between blue and orange and decided to follow the existing pattern for headings. But I lean towards blue as well. 😊

**Comment by DmitrySharabin** [comment]
Done. I also fixed issues with the layout for mobiles.

Please preview the changes here:
https://deploy-preview-137--mavoio.netlify.app/demos?demos-source=https://raw.githubusercontent.com/mavoweb/mavo.io/split-demos/demos/demos.json&mavos-source=https://raw.githubusercontent.com/mavoweb/mavo.io/split-demos/demos/mavos.json

**Review by LeaVerou — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
