### PR TITLE
[Demos] Migration from mv-edit* to mv-editor*

### PR DESCRIPTION
**Pull request by DmitrySharabin**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thank you!

**Comment by LeaVerou** [comment]
We should probably add a note somewhere that up to version [whatever the latest stable is] these attributes had a different name. Otherwise people using the latest stable will be very confused. And even after release, people might be on older versions, or people may be on the latest stable, discover their app is broken, and go to the docs to figure out how to fix it.

**Comment by DmitrySharabin** [comment]
I was thinking about that. And I agree with you.

I was also thinking about whether we should tweet about it.

And I am leaning towards the idea of adding a note to the docs as well. What do you think?

**Comment by LeaVerou** [comment]
Sure! But let's first add the note.

**Comment by LeaVerou** [comment]
And we need to iron out some minor regressions before tweeting about this. E.g. see: 
image

**Comment by DmitrySharabin** [comment]
> Sure! But let's first add the note.

What if we add a comment to the corresponding HTML files? So, we'll get something like that:

The _Talks list_ demo
```html
<!-- If you are using Mavo up to version 0.2.3, please replace mv-editor with mv-edit in the following tag. -->
<span property class="type" mv-editor="#talk-type"></span>
```
and
```html
<!-- If you are using Mavo up to version 0.2.3, please replace mv-editor with mv-edit in the following tag. -->
<span property="country" mv-editor="#countries"></span>
```

The _Restaurant visit log_ demo
```html
<!-- If you are using Mavo up to version 0.2.3, please replace mv-editor-step with mv-edit-step in the following tag. -->
<meter property="dishRating" min="0" value="4" max="5" mv-editor-step="0.5"></meter>
```

Or you had another way to add the note in your mind?

**Comment by LeaVerou** [comment]
That adds a lot of overhead to every single use of `mv-editor*`. 
I was just thinking of something like:

```
Note: In versions of Mavo up to 0.2.3 you will need to use `mv-edit` instead of `mv-editor` and `mv-edit-*` attributes instead of `mv-editor-*` attributes. 
```

**Comment by DmitrySharabin** [comment]
Oh, I see. I thought you meant we should add the note both in the demos and in the docs. So I sent a PR to the docs ([and already re-sent it with the text you suggested](https://github.com/mavoweb/mavo.io/pull/115)) and decided to discuss how to add the note to the demos. 😅 And if we don't need to add any comments, then I believe we are done with this PR, right?

**Pull request merged**
